apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sm-intel" # Fixed length characters to get lower
  namespace: "kubeflow-supermarket-production"
  labels:
    app: supermarket-intelligence
  annotations:
    serving.kserve.io/deploymentMode: RawDeployment
spec:
  predictor:
    containers:
      - name: "kserve-container"
        image: "mipjeiger/supermarket-kubeflow-pipeline:latest"
        command: ["python3", "-m", "Production.app.services.inference_gateway"]
        env:
          - name: "PYTHONPATH"
            value: "/app"
          - name: "ENV_PATH"
            value: "/app/.env"
        ports:
          - containerPort: 8085
            protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "1"
            memory: "2Gi"