FROM python:3.11-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    && rm -rf /var/lib/apt/lists/*

COPY requirements-api.txt /app/requirements-api.txt

RUN pip install --no-cache-dir -r requirements-api.txt

# Copy application code
COPY app/ ./app/
COPY Models/ ./Models/
COPY mlflow/ ./mlflow/

# Expose port
EXPOSE 8000

# Run the application
CMD ["uvicorn", "app.main:app", "--host", "0.0.0", "--port", "8000"]