FROM python:3.11-slim

WORKDIR /app

# Install MLFlow
RUN pip install --no-cache-dir mlflow

# Create mlflow directory
RUN mkdir -p /mlflow/artifacts

# Expose the MLFlow port
EXPOSE 5000

# Set MLFlow environment
ENV MLFLOW_TRACKING_URI=/mlflow

# Run MLFlow server
CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000", "--backend-store-uri", "/mlflow", "--default-artifact-root", "/mlflow/artifacts"]